### PR TITLE
provide the ability to have supplemental headers configured for endpoints.

### PR DESCRIPTION
**Pull request by wcjr**
would appreciate any of your feedback @sleepylemur @fillup before merging.

### CODE REVIEW

**Comment by sleepylemur** [comment]
What do you think about storing the additional headers as JSON?
I recently was using nginx to add a hard-coded authorization header to the backend service behind ApiAxle, and there was a `=` in the bearer token.

**Comment by wcjr** [comment]
That doesn't sound like a problem.  Instead of `"X-SPECIAL=1234,X-VENDOR-TYPE=abc,UNIQUE-VALUE=2js3j=123"`_(which would break)_ it would be
```
{
    X-SPECIAL: '1234',
    X-VENDOR-TYPE: 'abc',
    UNIQUE-VALUE: '2js3j=123'
}
```

Am I understanding you right @sleepylemur ?

**Comment by sleepylemur** [comment]
@wcjr yeah exactly. As a downside entering the json encoded field in a json api means a lot of backslashed double quotes, but it seems acceptable to me if you guys think it's a decent way to handle it.

**Comment by sleepylemur** [comment]
another option to consider would be urlencoding them... I was talking to a co-worker today and he was pretty anti double json encoding. whatever seems best to you.

**Comment by wcjr** [comment]
@sleepylemur I wonder if using single quotes would help avoid the extra escaping?  I can look into that as well as the urlencoding but I wonder if simply changing the '=' to a ':' in our original, comma-separated string would be an acceptable solution?  It would turn our original `"X-SPECIAL=1234,X-VENDOR-TYPE=abc,UNIQUE-VALUE=2js3j=123"` into `"X-SPECIAL:1234,X-VENDOR-TYPE:abc,UNIQUE-VALUE:2js3j=123"` _(do we ever see ':' in tokens?)_.  I really like the idea of the JSON so if single-quotes would resolve our problems, that would be my preference.  @forevermatt , do you have any preference?

**Comment by forevermatt** [comment]
IIRC, JSON technically requires double-quotes, so I don't know whether switching to single-quotes would be ideal. (I've hit situations where using single-quotes rather than double-quotes for JSON broke some JSON parser.) If we can find a clean way to use JSON, that seems like it would be great. If not, URL-encoding seems like a good option to me.

**Comment by wcjr** [comment]
Thanks @forevermatt , I'm going to see how redis handles a straight JSON object and will let you all know.  @sleepylemur , if we can do a straight JSON object, I don't think we'll need all the extra escaping since it won't be JSON serialized as a string.

**Comment by wcjr** [comment]
well, the API/REDIS support the straight JSON object, however the REPL doesn't.

```
curl -X PUT -H 'content-type: application/json' -d '{"additionalHeaders": {"X-HOMEY": "abc123", "UNIQUE": "123=123"}}' 'http://localhost:3100/v1/api/test'
{
  "meta": {
    "version": 1,
    "status_code": 200
  },
  "results": {
    "new": {
      "protocol": "http",
      "tokenSkewProtectionCount": 3,
      "apiFormat": "json",
      "endPointTimeout": 2,
      "disabled": false,
      "strictSSL": true,
      "sendThroughApiKey": false,
      "sendThroughApiSig": false,
      "hasCapturePaths": false,
      "allowKeylessUse": false,
      "keylessQps": 2,
      "keylessQpm": 120,
      "keylessQpd": 172800,
      "qps": 2,
      "qpm": -1,
      "qpd": 172800,
      "corsEnabled": false,
      "endPoint": "httpbin.org:80",
      "additionalHeaders": {
        "X-HOMEY": "abc123",
        "UNIQUE": "123=123"
      },
      "createdAt": 1474658509498,
      "defaultPath": "",
      "updatedAt": 1475069056424
    }
```

```
axle> api test update additionalHeaders={"X-HOMEY": "abc123", "UNIQUE": "123=123"}
Parser error: could not parse "{" (try quoting?)
axle>
```

I'm inclined to go forward with the JSON object for the API usage and open an issue against the REPL to support JSON objects as values.  **Any objections?**

**Comment by sleepylemur** [comment]
Redis doesn't support it easily because it only has flat hashmaps. Nothing nested. We could build support for nested json from the api by encoding/decoding on write/read. Not sure if it's more important to keep the api simple or the code simple. Probably the api is more important?

**Comment by wcjr** [comment]
I now see that even though the API responded as if it had stored the headers as an object, REDIS actually only has a string for the value `"[object Object]"`...bummer.  Since it has to be a string, maybe urlencoding is the best option here.

```
"X-SPECIAL=1234,X-VENDOR-TYPE=abc,UNIQUE-VALUE=2js3j=123"

would become this?

"X-SPECIAL=1234&X-VENDOR-TYPE=abc&UNIQUE-VALUE=2js3j%3D123"
```

**Comment by wcjr** [comment]
Went ahead with the idea of urlencoded string, let me know what you all think.

**Comment by sleepylemur** [comment]
Looks good to me 👍

**Pull request merged**
