### PR TITLE
Upgrade libxmljs to 0.18.x and hiredis to 0.5.0

### PR DESCRIPTION
**Pull request by robrich**
so it'll build on windows

### CODE REVIEW

**Comment by sleepylemur** [comment]
@robrich mind rebasing and resubmitting? also updating hiredis in base/package.json. thanks!

**Comment by fillup** [comment]
Hi @robrich, we've pulled in a bunch of changes the past couple weeks. Would you mind rebasing your PR so we can test and pull in?

**Comment by robrich** [comment]
@here: rebased.

**Comment by sleepylemur** [comment]
@fillup or @robrich, mind updating hiredis to the same version in base/package.json before merging? thanks!

**Comment by sleepylemur** [comment]
oops nevermind about the js2xml. we're using phil's version which has libxmljs updated to 0.18.0. should we delete apiaxle/js2xml if we're not using it for apiaxle?

**Comment by wcjr** [comment]
mos def homeslice!

**Comment by fillup** [comment]
@wcjr @sleepylemur sorry I got behind on this, is it good to merge or do we need to make some updates to hiredis?

**Comment by wcjr** [comment]
The code is good but @sleepylemur might be removing an unnecessary reference...

**Comment by sleepylemur** [comment]
we should update base/package.json hiredis to 0.5.0, and then it's good to go.

**Comment by wcjr** [comment]
@robrich , looks like @sleepylemur found a simple change...would you mind adding that to your PR?

**Comment by robrich** [comment]
done.

**Comment by fillup** [comment]
Thanks @robrich I'm finally getting this merged in, will be released as version 1.15.1.

**Pull request merged**
