### PR TITLE
Several updates from mapzen and silinternational

### PR DESCRIPTION
**Pull request by fillup**
This PR includes many changes from mapzen and silinternational. I believe the updates include:

 - Updated Docker support for development and production environments
 - Queries Per Minute support
 - External hit processors support
 - New all stats endpoint
 - Support for custom errors

There may be more, @sleepylemur would you mind commenting to provide more details about all your work included in this PR?

### CODE REVIEW

**Comment by sleepylemur** [comment]
In addition to above:
- allApis flag for keys
  -  set to true to allow a key to work with all apis.
- Cascading Limits
  - Limits can now be set on apis.
  - Limits on keys are now optional and considered overrides
  - New type of limit override `apiLimits` which allows api specific overrides for a key. Needed for keys that are used with multiple apis.
- Key and Api attributes are now removable by setting them to `null`
- Various minor bugfixes and cleanup

**Comment by fillup** [comment]
@sleepylemur is the `allApis` flag the same thing as `isNSA` with a less clever name?

http://apiaxle.com/api.html#/v1/key/:key

**Comment by sleepylemur** [comment]
Yes it's the same as isNSA flag except it is actually implemented

**Comment by wcjr** [comment]
Made api name matching configurable via apiNameRegex.

**Pull request merged**
